name: safe_password_generator
description: "A secure Flutter package for generating strong with support for multiple character sets and complexity rules"
version: 1.0.0
repository: https://github.com/piperfresh/safe_password_generator
issue_tracker: https://github.com/piperfresh/safe_password_generator/issues

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:


